

name: Build and Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      # If you're using actions/checkout@v2 you must set persist-credentials to
      # false in most cases for the deployment to work correctly.
      - name: Checkout 🛎️
        uses: actions/checkout@v2 
        with:
          persist-credentials: false
      # Use Node 14, Nextjs requires Node >= 12
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache  💾
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Install and Build 🔧
      - run: npm install
      - run: npm run build

      # Deploy
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: src/out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          
